PUSHCONST (20, NaN, NaN, NaN)
CALL uv
PUSHCONST (5, NaN, NaN, NaN)
BINOP -
BINOP *
SETVAR 0
PUSHCONST (0, NaN, NaN, NaN)
PUSHCONST (0, NaN, NaN, NaN)
PUSHCONST (10, NaN, NaN, NaN)
UNOP -
CALL float3
SETVAR 1
PUSHVAR 0
PUSHCONST (0, 0, 0, 0)
CALL swizzle
PUSHVAR 0
PUSHCONST (0, 0, 0, 0)
CALL swizzle
PUSHCONST (1, NaN, NaN, NaN)
CALL float3
CALL normalize
SETVAR 2
PUSHVAR 1
PUSHVAR 2
SETVAR 3
SETVAR 4
PUSHCONST (0, NaN, NaN, NaN)
SETVAR 5
PUSHCONST (0, NaN, NaN, NaN)
SETVAR 6
PUSHVAR 6
PUSHCONST (15, NaN, NaN, NaN)
BINOP <
CONDJUMP 202
PUSHVAR 4
PUSHVAR 5
PUSHVAR 3
BINOP *
BINOP +
SETVAR 7
PUSHVAR 7
CALL length
PUSHCONST (3, NaN, NaN, NaN)
BINOP -
SETVAR 8
PUSHVAR 7
PUSHCONST (2, NaN, NaN, NaN)
CALL time
PUSHCONST (0, 0, 0, 0)
CALL swizzle
CALL sin
PUSHCONST (3, NaN, NaN, NaN)
BINOP *
PUSHCONST (0, NaN, NaN, NaN)
CALL float3
BINOP +
CALL length
PUSHCONST (3, NaN, NaN, NaN)
BINOP -
SETVAR 9
PUSHVAR 8
PUSHVAR 9
PUSHCONST (5, NaN, NaN, NaN)
SETVAR 10
SETVAR 11
SETVAR 12
PUSHCONST (5, NaN, NaN, NaN)
PUSHCONST (5, NaN, NaN, NaN)
PUSHVAR 11
PUSHVAR 12
BINOP -
BINOP *
PUSHVAR 10
BINOP /
BINOP +
PUSHCONST (0, NaN, NaN, NaN)
PUSHCONST (10, NaN, NaN, NaN)
CALL clamp
SETVAR 13
PUSHVAR 11
PUSHVAR 12
PUSHVAR 13
CALL lerp
PUSHVAR 10
PUSHVAR 13
BINOP *
PUSHCONST (10, NaN, NaN, NaN)
PUSHVAR 13
BINOP -
BINOP *
BINOP -
SETVAR 14
PUSHVAR 5
PUSHVAR 14
BINOP +
SETVAR 5
PUSHVAR 6
PUSHCONST (1, NaN, NaN, NaN)
BINOP +
SETVAR 6
JUMP 60
PUSHVAR 5
SETVAR 15
PUSHVAR 15
PUSHCONST (1, NaN, NaN, NaN)
BINOP <
CONDJUMP 954
PUSHVAR 1
PUSHVAR 15
PUSHVAR 2
BINOP *
BINOP +
SETVAR 16
PUSHVAR 16
PUSHCONST (1, NaN, NaN, NaN)
PUSHCONST (0, NaN, NaN, NaN)
PUSHCONST (0, NaN, NaN, NaN)
CALL float3
BINOP +
SETVAR 7
PUSHVAR 7
CALL length
PUSHCONST (3, NaN, NaN, NaN)
BINOP -
SETVAR 8
PUSHVAR 7
PUSHCONST (2, NaN, NaN, NaN)
CALL time
PUSHCONST (0, 0, 0, 0)
CALL swizzle
CALL sin
PUSHCONST (3, NaN, NaN, NaN)
BINOP *
PUSHCONST (0, NaN, NaN, NaN)
CALL float3
BINOP +
CALL length
PUSHCONST (3, NaN, NaN, NaN)
BINOP -
SETVAR 9
PUSHVAR 8
PUSHVAR 9
PUSHCONST (5, NaN, NaN, NaN)
SETVAR 10
SETVAR 11
SETVAR 12
PUSHCONST (5, NaN, NaN, NaN)
PUSHCONST (5, NaN, NaN, NaN)
PUSHVAR 11
PUSHVAR 12
BINOP -
BINOP *
PUSHVAR 10
BINOP /
BINOP +
PUSHCONST (0, NaN, NaN, NaN)
PUSHCONST (10, NaN, NaN, NaN)
CALL clamp
SETVAR 13
PUSHVAR 11
PUSHVAR 12
PUSHVAR 13
CALL lerp
PUSHVAR 10
PUSHVAR 13
BINOP *
PUSHCONST (10, NaN, NaN, NaN)
PUSHVAR 13
BINOP -
BINOP *
BINOP -
PUSHVAR 16
PUSHCONST (1, NaN, NaN, NaN)
PUSHCONST (0, NaN, NaN, NaN)
PUSHCONST (0, NaN, NaN, NaN)
CALL float3
BINOP -
SETVAR 7
PUSHVAR 7
CALL length
PUSHCONST (3, NaN, NaN, NaN)
BINOP -
SETVAR 8
PUSHVAR 7
PUSHCONST (2, NaN, NaN, NaN)
CALL time
PUSHCONST (0, 0, 0, 0)
CALL swizzle
CALL sin
PUSHCONST (3, NaN, NaN, NaN)
BINOP *
PUSHCONST (0, NaN, NaN, NaN)
CALL float3
BINOP +
CALL length
PUSHCONST (3, NaN, NaN, NaN)
BINOP -
SETVAR 9
PUSHVAR 8
PUSHVAR 9
PUSHCONST (5, NaN, NaN, NaN)
SETVAR 10
SETVAR 11
SETVAR 12
PUSHCONST (5, NaN, NaN, NaN)
PUSHCONST (5, NaN, NaN, NaN)
PUSHVAR 11
PUSHVAR 12
BINOP -
BINOP *
PUSHVAR 10
BINOP /
BINOP +
PUSHCONST (0, NaN, NaN, NaN)
PUSHCONST (10, NaN, NaN, NaN)
CALL clamp
SETVAR 13
PUSHVAR 11
PUSHVAR 12
PUSHVAR 13
CALL lerp
PUSHVAR 10
PUSHVAR 13
BINOP *
PUSHCONST (10, NaN, NaN, NaN)
PUSHVAR 13
BINOP -
BINOP *
BINOP -
BINOP -
SETVAR 17
PUSHVAR 16
PUSHCONST (0, NaN, NaN, NaN)
PUSHCONST (1, NaN, NaN, NaN)
PUSHCONST (0, NaN, NaN, NaN)
CALL float3
BINOP +
SETVAR 7
PUSHVAR 7
CALL length
PUSHCONST (3, NaN, NaN, NaN)
BINOP -
SETVAR 8
PUSHVAR 7
PUSHCONST (2, NaN, NaN, NaN)
CALL time
PUSHCONST (0, 0, 0, 0)
CALL swizzle
CALL sin
PUSHCONST (3, NaN, NaN, NaN)
BINOP *
PUSHCONST (0, NaN, NaN, NaN)
CALL float3
BINOP +
CALL length
PUSHCONST (3, NaN, NaN, NaN)
BINOP -
SETVAR 9
PUSHVAR 8
PUSHVAR 9
PUSHCONST (5, NaN, NaN, NaN)
SETVAR 10
SETVAR 11
SETVAR 12
PUSHCONST (5, NaN, NaN, NaN)
PUSHCONST (5, NaN, NaN, NaN)
PUSHVAR 11
PUSHVAR 12
BINOP -
BINOP *
PUSHVAR 10
BINOP /
BINOP +
PUSHCONST (0, NaN, NaN, NaN)
PUSHCONST (10, NaN, NaN, NaN)
CALL clamp
SETVAR 13
PUSHVAR 11
PUSHVAR 12
PUSHVAR 13
CALL lerp
PUSHVAR 10
PUSHVAR 13
BINOP *
PUSHCONST (10, NaN, NaN, NaN)
PUSHVAR 13
BINOP -
BINOP *
BINOP -
PUSHVAR 16
PUSHCONST (0, NaN, NaN, NaN)
PUSHCONST (1, NaN, NaN, NaN)
PUSHCONST (0, NaN, NaN, NaN)
CALL float3
BINOP -
SETVAR 7
PUSHVAR 7
CALL length
PUSHCONST (3, NaN, NaN, NaN)
BINOP -
SETVAR 8
PUSHVAR 7
PUSHCONST (2, NaN, NaN, NaN)
CALL time
PUSHCONST (0, 0, 0, 0)
CALL swizzle
CALL sin
PUSHCONST (3, NaN, NaN, NaN)
BINOP *
PUSHCONST (0, NaN, NaN, NaN)
CALL float3
BINOP +
CALL length
PUSHCONST (3, NaN, NaN, NaN)
BINOP -
SETVAR 9
PUSHVAR 8
PUSHVAR 9
PUSHCONST (5, NaN, NaN, NaN)
SETVAR 10
SETVAR 11
SETVAR 12
PUSHCONST (5, NaN, NaN, NaN)
PUSHCONST (5, NaN, NaN, NaN)
PUSHVAR 11
PUSHVAR 12
BINOP -
BINOP *
PUSHVAR 10
BINOP /
BINOP +
PUSHCONST (0, NaN, NaN, NaN)
PUSHCONST (10, NaN, NaN, NaN)
CALL clamp
SETVAR 13
PUSHVAR 11
PUSHVAR 12
PUSHVAR 13
CALL lerp
PUSHVAR 10
PUSHVAR 13
BINOP *
PUSHCONST (10, NaN, NaN, NaN)
PUSHVAR 13
BINOP -
BINOP *
BINOP -
BINOP -
SETVAR 18
PUSHVAR 16
PUSHCONST (0, NaN, NaN, NaN)
PUSHCONST (0, NaN, NaN, NaN)
PUSHCONST (1, NaN, NaN, NaN)
CALL float3
BINOP +
SETVAR 7
PUSHVAR 7
CALL length
PUSHCONST (3, NaN, NaN, NaN)
BINOP -
SETVAR 8
PUSHVAR 7
PUSHCONST (2, NaN, NaN, NaN)
CALL time
PUSHCONST (0, 0, 0, 0)
CALL swizzle
CALL sin
PUSHCONST (3, NaN, NaN, NaN)
BINOP *
PUSHCONST (0, NaN, NaN, NaN)
CALL float3
BINOP +
CALL length
PUSHCONST (3, NaN, NaN, NaN)
BINOP -
SETVAR 9
PUSHVAR 8
PUSHVAR 9
PUSHCONST (5, NaN, NaN, NaN)
SETVAR 10
SETVAR 11
SETVAR 12
PUSHCONST (5, NaN, NaN, NaN)
PUSHCONST (5, NaN, NaN, NaN)
PUSHVAR 11
PUSHVAR 12
BINOP -
BINOP *
PUSHVAR 10
BINOP /
BINOP +
PUSHCONST (0, NaN, NaN, NaN)
PUSHCONST (10, NaN, NaN, NaN)
CALL clamp
SETVAR 13
PUSHVAR 11
PUSHVAR 12
PUSHVAR 13
CALL lerp
PUSHVAR 10
PUSHVAR 13
BINOP *
PUSHCONST (10, NaN, NaN, NaN)
PUSHVAR 13
BINOP -
BINOP *
BINOP -
PUSHVAR 16
PUSHCONST (0, NaN, NaN, NaN)
PUSHCONST (0, NaN, NaN, NaN)
PUSHCONST (1, NaN, NaN, NaN)
CALL float3
BINOP -
SETVAR 7
PUSHVAR 7
CALL length
PUSHCONST (3, NaN, NaN, NaN)
BINOP -
SETVAR 8
PUSHVAR 7
PUSHCONST (2, NaN, NaN, NaN)
CALL time
PUSHCONST (0, 0, 0, 0)
CALL swizzle
CALL sin
PUSHCONST (3, NaN, NaN, NaN)
BINOP *
PUSHCONST (0, NaN, NaN, NaN)
CALL float3
BINOP +
CALL length
PUSHCONST (3, NaN, NaN, NaN)
BINOP -
SETVAR 9
PUSHVAR 8
PUSHVAR 9
PUSHCONST (5, NaN, NaN, NaN)
SETVAR 10
SETVAR 11
SETVAR 12
PUSHCONST (5, NaN, NaN, NaN)
PUSHCONST (5, NaN, NaN, NaN)
PUSHVAR 11
PUSHVAR 12
BINOP -
BINOP *
PUSHVAR 10
BINOP /
BINOP +
PUSHCONST (0, NaN, NaN, NaN)
PUSHCONST (10, NaN, NaN, NaN)
CALL clamp
SETVAR 13
PUSHVAR 11
PUSHVAR 12
PUSHVAR 13
CALL lerp
PUSHVAR 10
PUSHVAR 13
BINOP *
PUSHCONST (10, NaN, NaN, NaN)
PUSHVAR 13
BINOP -
BINOP *
BINOP -
BINOP -
SETVAR 19
PUSHVAR 17
PUSHVAR 18
PUSHVAR 19
CALL float3
CALL normalize
PUSHCONST (5, NaN, NaN, NaN)
BINOP *
PUSHCONST (5, NaN, NaN, NaN)
BINOP +
JUMP 956
PUSHCONST (0, NaN, NaN, NaN)
